config/routes.rb
Rails.application.routes.draw do
  resources :survey_takers

  get 'pages/home'

  get 'about' => 'pages#about'

  get 'pages/help'

  get 'pages/contact'

  authenticated do
    root to: 'polls#index', as: :authenticated
  end

  unauthenticated do
    root :to => redirect('/home.html')
  end

  resources :polls

  match '/polls-history' => 'polls#history', :as => :polls_history, via: [:get]

  

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/survey_taker.rb
class SurveyTaker < ActiveRecord::Base

	def self.search(search)
		puts search.class
		where(number: search)
	end
end

app/controllers/survey_takers_controller.rb
require 'rest_client'
class SurveyTakersController < InheritedResources::Base
  def new
    @survey_taker = SurveyTaker.new
    #redirect_to root_url, notice: '#{name} - #{number}'
  end

  def create
    @survey_taker = SurveyTaker.new(survey_taker_params)
    @survey_taker.confirmed = 0

    resp = RestClient.get "https://staging.api.telstra.com/v1/oauth/token?client_id=" + Rails.application.secrets.telstra_public_key + "&client_secret=" + Rails.application.secrets.telstra_private_key + "&grant_type=client_credentials&scope=SMS"
    token = JSON.parse(resp)["access_token"]
    header =  {authorization: "Bearer #{token}", "Content-Type" => "application/json", "Accept" => "application/json"}
    puts "hello Brendon"
    name = params[:survey_taker][:name]
    number = params[:survey_taker][:number]
    puts name
    puts number

    result = JSON.parse(RestClient.post "https://staging.api.telstra.com/v1/sms/messages", {to: number, body: "#{name}, thank you for signing up. If you did not sign up, ignore this message. Otherwise reply with \"1\" to confirm"}.to_json, header)
    
    puts result
    puts result[:messageId]
    @survey_taker.message_id = result["messageId"]

    @survey_taker.save!

    respond_to do |format|
      if @survey_taker.update(survey_taker_params)
        format.html { redirect_to @survey_taker, notice: 'Successfully registered, awaiting verification.' }
        format.json { render :show, status: :ok, location: @survey_taker }
      else
        format.html { render :edit }
        format.json { render json: @survey_taker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @survey_taker.update(survey_taker_params)
        format.html { redirect_to root_url, notice: 'survey_taker was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_taker }
      else
        format.html { render :edit }
        format.json { render json: @survey_taker.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    if params[:number]
      @survey_takers = SurveyTaker.search(params[:number].to_s)
      if @survey_takers.first.confirmed == 0
        resp = RestClient.get "https://staging.api.telstra.com/v1/oauth/token?client_id=" + Rails.application.secrets.telstra_public_key + "&client_secret=" + Rails.application.secrets.telstra_private_key + "&grant_type=client_credentials&scope=SMS"
        puts "https://staging.api.telstra.com/v1/oauth/token?client_id=" + Rails.application.secrets.telstra_public_key + "&client_secret=" + Rails.application.secrets.telstra_private_key + "&grant_type=client_credentials&scope=SMS"
        token = JSON.parse(resp)["access_token"]
        header =  {authorization: "Bearer " + token, "Content-Type" => "application/json", "Accept" => "application/json"}

        address = "https://staging.api.telstra.com/v1/sms/messages/"+ @survey_takers.first.message_id + "/response"
        puts address
        response = RestClient.get(address, header)
        result = JSON.parse(response)[0]

        if result["content"][0] == "1"
          @survey_takers.first.confirmed = 1
          @survey_takers.first.save!
        end
      end
    else
      @survey_takers = nil
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @survey_taker.save!
    respond_to do |format|
      format.html { redirect_to survey_taker_url, notice: 'survey_taker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    @survey_taker = SurveyTaker.find_by_id(params[:id])
    if @survey_taker.confirmed == 0
      resp = RestClient.get "https://staging.api.telstra.com/v1/oauth/token?client_id=" + Rails.application.secrets.telstra_public_key + "&client_secret=" + Rails.application.secrets.telstra_private_key + "&grant_type=client_credentials&scope=SMS"
      token = JSON.parse(resp)["access_token"]
      header =  {authorization: "Bearer #{token}", "Content-Type" => "application/json", "Accept" => "application/json"}
      puts ":::" + @survey_taker.message_id + ":::"
      response = RestClient.get("https://staging.api.telstra.com/v1/sms/messages/"+ @survey_taker.message_id + "/response", header){|response, request, result| response }
      result = JSON.parse(response)[0]
      #puts "Result:" + @result
      puts "----------------------------------------------------------------------"
      if (not result.nil?) && result["content"][0] == "1"
        @survey_taker.confirmed = 1
        @survey_taker.save!
      end
    end
  end

  private

    def survey_taker_params
      params.require(:survey_taker).permit(:name, :number, :message_id, :confirmed)
    end
end

app/helpers/survey_takers_helper.rb
module SurveyTakersHelper
end

app/views/survey_takers/_find.html.erb
<%= form_tag(survey_takers_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :number, params[:number], placeholder: "Phone Number" %>
<%= submit_tag "Login" %>
<% end %>

app/views/survey_takers/_form.html.erb
<%= simple_form_for(@survey_taker,  html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
	    <%= f.input :name, class: "text-field form-control", html: {spellcheck: "false"} %>
  </div>

  <div class="form-group">
	    <%= f.input :number, class: "bfh-phone form-control", "data-format" => "dddd-ddd-ddd", html: {spellcheck: "false"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Register" %>
  </div>
<% end %>

app/views/survey_takers/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Survey Taker</h3>
                    </div>                      
                    <div class="panel-body">
                        <% if @survey_takers.nil? && params[:search].nil? %>
                            <%= render partial: "find" %>
                        <% elsif @survey_takers.nil? or @survey_takers.count == 0 %>
                            <p>
                                Could not find any registrations with that number.
                            </p>
                            <%= render partial: "find" %>
                        <% else %>
                            <h4><%= @survey_takers.first.number %></h4>
                            <p>
                                <% if @survey_takers.first.confirmed == 0 %>
                                    Please confirm your account.
                                <% else %>
                                    Your account has been activated.
                                <% end %>
                            </p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/survey_takers/new.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Sign up</h3>
                    </div>                      
                    <div class="panel-body">
                      <%= render 'form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/survey_takers/show.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><%= @survey_taker.number %></h3>
                    </div>                      
                    <div class="panel-body">
                        <p>
                        <% if @survey_taker.confirmed == 0 %>
                            Please confirm your account.
                        <% else %>
                            Your account has been activated. You will receive surveys to your phone via SMS now.
                        <% end %>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>