config/routes.rb
Rails.application.routes.draw do
  resources :survey_takers

  get 'pages/home'

  get 'about' => 'pages#about'

  get 'pages/help'

  get 'pages/contact'

  authenticated do
    root to: 'polls#index', as: :authenticated
  end

  unauthenticated do
    root :to => redirect('/home.html')
  end

  resources :polls

  match '/polls-history' => 'polls#history', :as => :polls_history, via: [:get]

  

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/elements/_copyright.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <i>Ur Say</i> Copywright © <%= Time.now.year %>
    </div>

    <!-- /.panel-body -->
</div>
<!-- /.panel -->

app/views/elements/_current_history.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-history fa-fw"></i> <%= link_to "Current Polls", polls_url %>
    </div>
    <div class="panel-body">
        <% history = Poll.where(user_id: current_user).where("end_date > ?", Date.today) %>
        <% if (not history.nil?) and (history.length > 0) %>
            <table class="table table-striped">
            <thead>
                <th>Question</th>
                <th>Votes</th>
                <th>Dates</th>
            </thead>
            <tbody>
                <% history.each do |poll| %>
                    <tr>
                        <td><%= link_to poll.question, poll %></td>
                        <td><%= poll.votes %></td>
                        <td><%= poll.end_date.to_formatted_s(:long_ordinal) %></td>
                    <tr/>
                <% end %>
            </tbody>
            </table>
        <% else %>
            <p>No previous polls</p>
        <% end %>
    </div>
</div>

app/views/elements/_dashboard.html.erb
<!-- /.row -->
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">$124</div>
                        <div>Invoice charged</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= count_votes current_user %></div>
                        <div>Total Votes</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-clipboard fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= Poll.where(user_id: current_user).where("end_date > ?", Date.today).count %></div>
                        <div>Polls being run</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-history fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= Poll.where(user_id: current_user).where("end_date < ?", Date.today).count %></div>
                        <div>Previous polls</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Ur Say", root_url, class: "navbar-brand" %>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!--li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li-->
                <!-- /.dropdown -->
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <%= link_to raw('<i class="fa fa-user fa-fw"></i> User Profile'), edit_user_registration_path %>
                        </li>
                        <li class="divider"></li>
                            <%= link_to raw('<i class="fa fa-sign-out fa-fw"></i> Logout'), destroy_user_session_path, method: :delete %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <%= link_to raw('<i class="fa fa-dashboard fa-fw"></i> Current Polls'), root_url %>
                        </li>
                        <li>
                        <%= link_to raw('<i class="fa fa-history fa-fw"></i> Past Polls'), polls_history_url %>
                        </li>
                        <li>
                        <%= link_to raw('<i class="fa fa-dollar fa-fw"></i> Billings'), root_url %>
                        </li>

                        <li>
                        <%= link_to raw('<i class="fa fa-info fa-fw"></i> About'), about_url %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/elements/_new_poll.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-edit fa-fw"></i> <%= link_to "New Poll", new_poll_url %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <% @poll = Poll.new %>
        <%= render partial: "polls/form" %>
    </div>
    <!-- /.panel-body -->
</div>

app/views/elements/_small_history.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-history fa-fw"></i> <%= link_to "Past Polls", polls_history_url %>
    </div>
    <div class="panel-body">
        <% history = Poll.where(user_id: current_user).where("(end_date < ?) OR (end_date = ?)", Date.today, Date.today) %>
        <% if (not history.nil?) and (history.length > 0) %>
            <table class="table table-striped">
            <thead>
                <th>Question</th>
                <th>Votes</th>
                <th>Dates</th>
            </thead>
            <tbody>
                <% history.each do |poll| %>
                    <tr>
                        <td><%= link_to poll.question, poll %></td>
                        <td><%= poll.votes %></td>
                        <td><%= poll.end_date.to_formatted_s(:long_ordinal) %></td>
                    <tr/>
                <% end %>
            </tbody>
            </table>
        <% else %>
            <p>No previous polls</p>
        <% end %>
    </div>
</div>